### ISSUE TITLE
Banned by mistake

### ISSUE THREAD

**Issue by jpresutti** [OrlandoDevs/orlandodevs.github.io#69]
I think something went wrong on slack. I was banned without violation of any rules. Probably a technical glitch. Please resolve.

Edit to add: I was not even online or sent any message at the time of the ban.

**Comment by JimmyVo16** [comment]
If this ban was intended then I think a public explanation is warranted. I'm not challenging the decision to ban this person, but I think all bans should be public with an explanation for the ban and any supporting documentations. Here are the benefits of being transparent.

1. The banned person will know what they did wrong. 
2. Other folks can see the consequences of these types of behaviors. This will deter others from behaving the same way.  
3. It will reduce abuse of power. You can't ban people because you don't like them. You need to explain to the public for that ban.
4. The transparency will increase trust. 
5. You can also provide documentations that the banned person had been warned, but choose to continue the behavior.

**Comment by Boricua1990** [comment]
I'm with Jimmy, especially on #4 and #5. Without those two things, anyone could be banned for any reason just because and this implies that the admins of the community are abusing their power to bully people they do not like.

Few questions:

- What is the standard ban process for this community?
- Are there warnings involved? Probationary periods? If not, why not?
- Do admins reach out before the ban to ensure the person is aware of why and allow them to make a final appeal? If not, why not?
- Is there a ban appeal process? Who oversees this? If not, why not?
- Are we making sure that the person overseeing ban appeals is not the same person that issued the ban? To show that there is no bias in denying the appeal, if all board members agreed to the ban, then its only fair you must all be present at their appeal. If not, why not?

I'm really confident had Jeremy been warned of anything prior to this ban would of never been issued.

I get some bans are spur of the moment like outside of "some guy logged on and spammed nonstop" or "some guy joined and kept saying profane / highly offensive things" but if you've been a member for years and years, there should be a process before the rug is pulled underneath you.

Very importantly someone shouldn't not know why they're banned. **This creates a sense of worry that admins are abusing their abilities over members they don't like** and are using their abilities to harass said members.

I get managing a community is complicated, I've managed much larger communities than Orlando Devs (thousands of daily active users) so I understand the struggle of maintaining a certain environment, but you'd be surprised how much more fruitful it is to talk to someone before excluding them from your community permanently.

Ban bad behavior not human beings. Be transparent, otherwise some of us will assume the worst.

**Comment by stuffmattdoes** [comment]
Same for me. Noticed I was unable to log in one day. I had no prior contact (let alone warnings) with mods prior to being locked out, so I'm sure it was a mistake.

**Comment by adamkarb** [comment]
I was directed to this issue from a friend. My slack disconnected that day too, I was wondering if it was just a mistake or something involving an email list. I’ve been in odevs for 7-8 years now and no one representing odevs has ever contacted me about anything related to behavior, so I doubt I was removed purposefully. Let me know what is going on, thanks.

**Comment by jacquesfu** [comment]
Hey there! Apologies, I missed this issue.

Our board of advisors collectively discuss recommendations provided by moderators.

Here's how it works when a moderator observes or someone reports behavior not consistent with CoC.

- Violations of our CoC are first addressed privately with the member.
- The moderator may then delete the offending material or leave it if it is "instructive" to other community members along with a generic reminder to adhere to our CoC.
- If a member refuses to cease or after repeated violations (this isn't any specific time period), a moderator may recommend banning due to a history of non-compliance with CoC.
- The evidence will be screenshot and shared with our board. This means every ban is discussed amongst the board.
- If there is a consensus, then the member will be banned.
- The member can appeal the decision and also be re-instated after a time if they reach out and the board believes that they are willing to take corrective actions on their behavior (or re-instated if it was in error).

Without naming names, I believe some of the folks in this thread have had numerous warnings spanning years without a ban or probationary period that I'm aware of.  (EDIT: I was reminded there was a temporary suspension for some of the banned persons)

In particular, the most recent bannings were due to targeted harassment of another member due to their background. As a reminder our CoC states, "Be welcoming: We strive to be a community that welcomes and supports people of all backgrounds and identities. This includes, but is not limited to members of any race, ethnicity, culture, national origin, color, immigration status, social and economic class, educational level, sex, sexual orientation, gender identity and expression, age, size, family status, political belief, religion, and mental and physical ability."

Also, our first mandate is to "Be friendly and patient" so even if there are gray areas, being friendly is generally clear guidance.

For clarity, I plan to email everyone I believe to be impacted in the day or two. You can respond with any questions or appeal. If you prefer me to share the timeline and reasoning behind the decision publicly I would need permission from you and the affected parties.

**Comment by jacquesfu** [comment]
> I get managing a community is complicated, I've managed much larger communities than Orlando Devs (thousands of daily active users) so I understand the struggle of maintaining a certain environment

As an aside @Boricua1990 if you have any moderation tools you recommend for slack please let me know, thanks!

**Comment by jpresutti** [comment]
It's quite funny that you admit in private that we did not do what your initial email says we did, but you're pretending publicly we did. Honestly, pretty tacky.
